version: '3'
services:
  app:
    depends_on:
      - db
    image: transcribee
    ports:
      - "5173:5173"
    environment:
      - TRANSCRIBEE_BACKEND_DATABASE_URL=postgresql://transcribee:transcribee@db:5432/transcribee
    volumes:
      - ./:/app
    entrypoint: ["nix-shell", "shell.nix", "--command", "/app/packaging/dev.sh"]

  db:
    image: postgres:14
    environment:
      POSTGRES_USER: transcribee
      POSTGRES_PASSWORD: transcribee
      POSTGRES_DB: transcribee
    volumes:
      - ./backend/db:/var/lib/postgresql/data
